FROM python:3.14.0-slim-trixie
WORKDIR /self-awareness/hardware_info
COPY script.py ./
RUN apt update
RUN apt install -y gcc iproute2 python3-dev
RUN pip3 install getmac psutil quart requests speedtest-cli
EXPOSE 8002
ENTRYPOINT [ "python3", "-u", "script.py" ]
